USE BD_CASTILLON_VETERINARIA;
GO

-- CATEGORIA
IF OBJECT_ID('dbo.CATEGORIA','U') IS NULL
BEGIN
  CREATE TABLE dbo.CATEGORIA(
    IDCATEGORIA  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMCATEGORIA VARCHAR(100) NOT NULL,
    ESTADO       CHAR(1) NULL DEFAULT '1'
  );
END
GO

IF NOT EXISTS (SELECT 1 FROM CATEGORIA)
BEGIN
  INSERT INTO CATEGORIA (NOMCATEGORIA, ESTADO) VALUES ('Medicamentos', '1');
  INSERT INTO CATEGORIA (NOMCATEGORIA, ESTADO) VALUES ('Alimentos', '1');
  INSERT INTO CATEGORIA (NOMCATEGORIA, ESTADO) VALUES ('Accesorios', '1');
  INSERT INTO CATEGORIA (NOMCATEGORIA, ESTADO) VALUES ('Higiene', '1');
  INSERT INTO CATEGORIA (NOMCATEGORIA, ESTADO) VALUES ('Vacunas', '1');
END
GO

-- UNIDAD_MEDIDA
IF OBJECT_ID('dbo.UNIDAD_MEDIDA','U') IS NULL
BEGIN
  CREATE TABLE dbo.UNIDAD_MEDIDA(
    IDUNIDAD_MEDIDA  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMUNIDAD_MEDIDA VARCHAR(100) NOT NULL,
    ESTADO           CHAR(1) NULL DEFAULT '1'
  );
END
GO

IF NOT EXISTS (SELECT 1 FROM UNIDAD_MEDIDA)
BEGIN
  INSERT INTO UNIDAD_MEDIDA (NOMUNIDAD_MEDIDA, ESTADO) VALUES ('Unidad', '1');
  INSERT INTO UNIDAD_MEDIDA (NOMUNIDAD_MEDIDA, ESTADO) VALUES ('Caja', '1');
  INSERT INTO UNIDAD_MEDIDA (NOMUNIDAD_MEDIDA, ESTADO) VALUES ('Frasco', '1');
  INSERT INTO UNIDAD_MEDIDA (NOMUNIDAD_MEDIDA, ESTADO) VALUES ('Bolsa', '1');
  INSERT INTO UNIDAD_MEDIDA (NOMUNIDAD_MEDIDA, ESTADO) VALUES ('Kilogramo', '1');
END
GO
