-- ============================================================
-- Inicializacion de bases de datos para el Sistema Consolidado
-- Crea las BDs, tablas PRODUCTO_CONSOLIDADO (con VERSION y
-- Soft Delete), OUTBOX, y las tablas de origen.
-- ============================================================

IF DB_ID('CASTILLONV2')                            IS NULL CREATE DATABASE CASTILLONV2;
IF DB_ID('BD_CASTILLON_VETERINARIA')               IS NULL CREATE DATABASE BD_CASTILLON_VETERINARIA;
IF DB_ID('BD_CONSOLIDADO')                         IS NULL CREATE DATABASE BD_CONSOLIDADO;
GO

-- ------------------------------------------------------------
-- CASTILLONV2.PRODUCTO
-- ------------------------------------------------------------
USE CASTILLONV2;
GO
IF OBJECT_ID('dbo.CATEGORIA','U') IS NULL
BEGIN
  CREATE TABLE dbo.CATEGORIA(
    IDCATEGORIA  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMCATEGORIA VARCHAR(80) NULL,
    ESTADO       CHAR(1) NULL DEFAULT '1'
  );
END
GO
IF NOT EXISTS (SELECT 1 FROM CATEGORIA)
BEGIN
  INSERT INTO CATEGORIA (NOMCATEGORIA, ESTADO) VALUES ('Bebidas', '1');
  INSERT INTO CATEGORIA (NOMCATEGORIA, ESTADO) VALUES ('Platos', '1');
  INSERT INTO CATEGORIA (NOMCATEGORIA, ESTADO) VALUES ('Condimentos', '1');
END
GO
IF OBJECT_ID('dbo.PRODUCTO','U') IS NULL
BEGIN
  CREATE TABLE dbo.PRODUCTO(
    IDPRODUCTO   INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IDCATEGORIA  INT NULL,
    NOMPRODUCTO  NVARCHAR(100) NULL,
    DESCRIPCION  NVARCHAR(100) NULL,
    PRECIO       DECIMAL(10,2) NULL,
    MARCA        NVARCHAR(50)  NULL,
    ESTADO       CHAR(1)       NULL
  );
END
GO
IF NOT EXISTS (SELECT 1 FROM PRODUCTO)
BEGIN
  INSERT INTO PRODUCTO (IDCATEGORIA, NOMPRODUCTO, DESCRIPCION, PRECIO, MARCA, ESTADO)
  VALUES (1, 'Gaseosa 500ml', 'Bebida gasificada', 3.50, 'Inca Kola', '1');
  INSERT INTO PRODUCTO (IDCATEGORIA, NOMPRODUCTO, DESCRIPCION, PRECIO, MARCA, ESTADO)
  VALUES (2, 'Lomo Saltado', 'Plato de fondo', 25.00, 'SIN MARCA', '1');
  INSERT INTO PRODUCTO (IDCATEGORIA, NOMPRODUCTO, DESCRIPCION, PRECIO, MARCA, ESTADO)
  VALUES (3, 'Salsa Verde', 'Condimento casero', 8.00, 'Frankfurter', '1');
END
GO

-- CASTILLONV2.PERSONA + EMPRESA + CLIENTE (origen del ETL de clientes)
IF OBJECT_ID('dbo.PERSONA','U') IS NULL
BEGIN
  CREATE TABLE dbo.PERSONA(
    IDPERSONA   INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMBRES     VARCHAR(80) NULL,
    APEPATERNO  VARCHAR(70) NULL,
    APEMATERNO  VARCHAR(70) NULL,
    ESTADO      CHAR(1) NULL DEFAULT '1'
  );
END
GO
IF NOT EXISTS (SELECT 1 FROM PERSONA)
BEGIN
  INSERT INTO PERSONA (NOMBRES, APEPATERNO, APEMATERNO) VALUES ('Ana', 'Flores', 'Vega');
  INSERT INTO PERSONA (NOMBRES, APEPATERNO, APEMATERNO) VALUES ('Luis', 'Quispe', 'Ramos');
END
GO
IF OBJECT_ID('dbo.EMPRESA','U') IS NULL
BEGIN
  CREATE TABLE dbo.EMPRESA(
    IDEMPRESA    INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    RUC          CHAR(11) NULL,
    RAZON_SOCIAL NVARCHAR(90) NULL,
    ESTADO       CHAR(1) NULL DEFAULT '1'
  );
END
GO
IF NOT EXISTS (SELECT 1 FROM EMPRESA)
  INSERT INTO EMPRESA (RUC, RAZON_SOCIAL) VALUES ('20123456789', 'Comercial Samar SAC');
GO
IF OBJECT_ID('dbo.CLIENTE','U') IS NULL
BEGIN
  CREATE TABLE dbo.CLIENTE(
    IDCLIENTE  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IDPERSONA  INT NULL,
    IDEMPRESA  INT NULL,
    ESTADO     CHAR(1) NULL DEFAULT '1'
  );
END
GO
IF NOT EXISTS (SELECT 1 FROM CLIENTE)
BEGIN
  INSERT INTO CLIENTE (IDPERSONA, IDEMPRESA) VALUES (1, NULL);
  INSERT INTO CLIENTE (IDPERSONA, IDEMPRESA) VALUES (2, 1);
END
GO

-- ------------------------------------------------------------
-- BD_CASTILLON_VETERINARIA.PRODUCTO
-- ------------------------------------------------------------
USE BD_CASTILLON_VETERINARIA;
GO
IF OBJECT_ID('dbo.PRODUCTO','U') IS NULL
BEGIN
  CREATE TABLE dbo.PRODUCTO(
    IDPRODUCTO       INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IDUNIDAD_MEDIDA  INT NULL,
    IDCATEGORIA      INT NULL,
    NOMPRODUCTO      VARCHAR(100) NOT NULL,
    DESCRIPCION      NVARCHAR(250) NULL,
    PRECIO_UNITARIO  DECIMAL(10,2) NOT NULL,
    STOCK_ACTUAL     INT NULL,
    USUCRE           VARCHAR(30) NULL,
    PCCRE            VARCHAR(30) NULL,
    FECCRE           DATETIME NULL,
    USUMOD           VARCHAR(30) NULL,
    PCMOD            VARCHAR(30) NULL,
    FECMOD           DATETIME NULL,
    ESTADO           CHAR(1) NULL
  );
END
GO

-- ------------------------------------------------------------
-- BD_CASTILLON_VETERINARIA.CATEGORIA
-- ------------------------------------------------------------
IF OBJECT_ID('dbo.CATEGORIA','U') IS NULL
BEGIN
  CREATE TABLE dbo.CATEGORIA(
    IDCATEGORIA  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMCATEGORIA VARCHAR(100) NOT NULL,
    ESTADO       CHAR(1) NULL DEFAULT '1'
  );
END
GO
IF NOT EXISTS (SELECT 1 FROM CATEGORIA)
BEGIN
  INSERT INTO CATEGORIA (NOMCATEGORIA) VALUES ('Medicamentos');
  INSERT INTO CATEGORIA (NOMCATEGORIA) VALUES ('Alimentos');
  INSERT INTO CATEGORIA (NOMCATEGORIA) VALUES ('Accesorios');
  INSERT INTO CATEGORIA (NOMCATEGORIA) VALUES ('Higiene');
  INSERT INTO CATEGORIA (NOMCATEGORIA) VALUES ('Vacunas');
END
GO

-- ------------------------------------------------------------
-- BD_CASTILLON_VETERINARIA.UNIDAD_MEDIDA
-- ------------------------------------------------------------
IF OBJECT_ID('dbo.UNIDAD_MEDIDA','U') IS NULL
BEGIN
  CREATE TABLE dbo.UNIDAD_MEDIDA(
    IDUNIDAD_MEDIDA  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMUNIDAD_MEDIDA VARCHAR(100) NOT NULL,
    ESTADO           CHAR(1) NULL DEFAULT '1'
  );
END
GO
IF NOT EXISTS (SELECT 1 FROM UNIDAD_MEDIDA)
BEGIN
  INSERT INTO UNIDAD_MEDIDA (NOMUNIDAD_MEDIDA) VALUES ('Unidad');
  INSERT INTO UNIDAD_MEDIDA (NOMUNIDAD_MEDIDA) VALUES ('Caja');
  INSERT INTO UNIDAD_MEDIDA (NOMUNIDAD_MEDIDA) VALUES ('Frasco');
  INSERT INTO UNIDAD_MEDIDA (NOMUNIDAD_MEDIDA) VALUES ('Bolsa');
  INSERT INTO UNIDAD_MEDIDA (NOMUNIDAD_MEDIDA) VALUES ('Kilogramo');
END
GO

-- ------------------------------------------------------------
-- BD_CASTILLON_VETERINARIA.ESPECIE
-- ------------------------------------------------------------
IF OBJECT_ID('dbo.ESPECIE','U') IS NULL
BEGIN
  CREATE TABLE dbo.ESPECIE(
    IDESPECIE  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMESPECIE VARCHAR(100) NOT NULL,
    ESTADO     CHAR(1) NULL DEFAULT '1'
  );
END
GO
IF NOT EXISTS (SELECT 1 FROM ESPECIE)
BEGIN
  INSERT INTO ESPECIE (NOMESPECIE) VALUES ('Canino');
  INSERT INTO ESPECIE (NOMESPECIE) VALUES ('Felino');
  INSERT INTO ESPECIE (NOMESPECIE) VALUES ('Ave');
END
GO

-- ------------------------------------------------------------
-- BD_CASTILLON_VETERINARIA.RAZA
-- ------------------------------------------------------------
IF OBJECT_ID('dbo.RAZA','U') IS NULL
BEGIN
  CREATE TABLE dbo.RAZA(
    IDRAZA    INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IDESPECIE INT NULL,
    NOMRAZA   VARCHAR(100) NOT NULL,
    ESTADO    CHAR(1) NULL DEFAULT '1'
  );
END
GO
IF NOT EXISTS (SELECT 1 FROM RAZA)
BEGIN
  INSERT INTO RAZA (IDESPECIE, NOMRAZA) VALUES (1, 'Labrador');
  INSERT INTO RAZA (IDESPECIE, NOMRAZA) VALUES (1, 'Pastor Aleman');
  INSERT INTO RAZA (IDESPECIE, NOMRAZA) VALUES (1, 'Bulldog');
  INSERT INTO RAZA (IDESPECIE, NOMRAZA) VALUES (2, 'Persa');
  INSERT INTO RAZA (IDESPECIE, NOMRAZA) VALUES (2, 'Siames');
  INSERT INTO RAZA (IDESPECIE, NOMRAZA) VALUES (3, 'Canario');
END
GO

-- ------------------------------------------------------------
-- BD_CASTILLON_VETERINARIA.PERSONA
-- ------------------------------------------------------------
IF OBJECT_ID('dbo.PERSONA','U') IS NULL
BEGIN
  CREATE TABLE dbo.PERSONA(
    IDPERSONA    INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    NOMBRE       VARCHAR(100) NOT NULL,
    APE_PATERNO  VARCHAR(100) NULL,
    APE_MATERNO  VARCHAR(100) NULL,
    TELEFONO     VARCHAR(20) NULL,
    ESTADO       CHAR(1) NULL DEFAULT '1'
  );
END
GO
IF NOT EXISTS (SELECT 1 FROM PERSONA)
BEGIN
  INSERT INTO PERSONA (NOMBRE, APE_PATERNO, APE_MATERNO) VALUES ('Juan', 'Castillon', 'Lopez');
  INSERT INTO PERSONA (NOMBRE, APE_PATERNO, APE_MATERNO) VALUES ('Maria', 'Garcia', 'Torres');
  INSERT INTO PERSONA (NOMBRE, APE_PATERNO, APE_MATERNO) VALUES ('Carlos', 'Mendez', 'Rios');
END
GO

-- ------------------------------------------------------------
-- BD_CASTILLON_VETERINARIA.EMPRESA + CLIENTE (origen del ETL de clientes)
-- ------------------------------------------------------------
IF OBJECT_ID('dbo.EMPRESA','U') IS NULL
BEGIN
  CREATE TABLE dbo.EMPRESA(
    IDEMPRESA    INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    RUC          VARCHAR(11) NULL,
    RAZON_SOCIAL VARCHAR(50) NULL,
    ESTADO       CHAR(1) NULL DEFAULT '1'
  );
END
GO
IF OBJECT_ID('dbo.CLIENTE','U') IS NULL
BEGIN
  CREATE TABLE dbo.CLIENTE(
    IDCLIENTE  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IDPERSONA  INT NULL,
    IDEMPRESA  INT NULL,
    ESTADO     CHAR(1) NULL DEFAULT '1'
  );
END
GO
IF NOT EXISTS (SELECT 1 FROM CLIENTE)
BEGIN
  INSERT INTO CLIENTE (IDPERSONA, IDEMPRESA) VALUES (1, NULL);
  INSERT INTO CLIENTE (IDPERSONA, IDEMPRESA) VALUES (2, NULL);
  INSERT INTO CLIENTE (IDPERSONA, IDEMPRESA) VALUES (3, NULL);
END
GO

-- ------------------------------------------------------------
-- BD_CASTILLON_VETERINARIA.MASCOTA
-- ------------------------------------------------------------
IF OBJECT_ID('dbo.MASCOTA','U') IS NULL
BEGIN
  CREATE TABLE dbo.MASCOTA(
    IDMASCOTA  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IDPERSONA  INT NULL,
    IDRAZA     INT NULL,
    GENERO     VARCHAR(20) NULL,
    COLOR      VARCHAR(50) NULL,
    FECHNAC    DATE NULL,
    PESO       DECIMAL(10,2) NULL,
    ESTADO     CHAR(1) NULL DEFAULT '1'
  );
END
GO
IF NOT EXISTS (SELECT 1 FROM MASCOTA)
BEGIN
  INSERT INTO MASCOTA (IDPERSONA, IDRAZA, GENERO, COLOR, FECHNAC, PESO) VALUES (1, 1, 'Macho', 'Dorado', '2022-03-15', 25.50);
  INSERT INTO MASCOTA (IDPERSONA, IDRAZA, GENERO, COLOR, FECHNAC, PESO) VALUES (2, 4, 'Hembra', 'Blanco', '2023-07-20', 4.20);
  INSERT INTO MASCOTA (IDPERSONA, IDRAZA, GENERO, COLOR, FECHNAC, PESO) VALUES (3, 2, 'Macho', 'Negro', '2021-11-10', 30.00);
  INSERT INTO MASCOTA (IDPERSONA, IDRAZA, GENERO, COLOR, FECHNAC, PESO) VALUES (1, 5, 'Hembra', 'Gris', '2024-01-05', 3.80);
END
GO

-- Datos de ejemplo para PRODUCTO
IF NOT EXISTS (SELECT 1 FROM PRODUCTO)
BEGIN
  INSERT INTO PRODUCTO (IDUNIDAD_MEDIDA, IDCATEGORIA, NOMPRODUCTO, DESCRIPCION, PRECIO_UNITARIO, STOCK_ACTUAL, ESTADO, USUCRE, PCCRE, FECCRE)
  VALUES (3, 1, 'Amoxicilina 500mg', 'Antibiotico de amplio espectro', 25.50, 100, '1', 'admin', 'PC01', GETDATE());
  INSERT INTO PRODUCTO (IDUNIDAD_MEDIDA, IDCATEGORIA, NOMPRODUCTO, DESCRIPCION, PRECIO_UNITARIO, STOCK_ACTUAL, ESTADO, USUCRE, PCCRE, FECCRE)
  VALUES (2, 2, 'ProPlan Adulto 15kg', 'Alimento premium para perros adultos', 189.90, 50, '1', 'admin', 'PC01', GETDATE());
  INSERT INTO PRODUCTO (IDUNIDAD_MEDIDA, IDCATEGORIA, NOMPRODUCTO, DESCRIPCION, PRECIO_UNITARIO, STOCK_ACTUAL, ESTADO, USUCRE, PCCRE, FECCRE)
  VALUES (1, 3, 'Collar Antipulgas', 'Collar antipulgas para perros medianos', 35.00, 75, '1', 'admin', 'PC01', GETDATE());
  INSERT INTO PRODUCTO (IDUNIDAD_MEDIDA, IDCATEGORIA, NOMPRODUCTO, DESCRIPCION, PRECIO_UNITARIO, STOCK_ACTUAL, ESTADO, USUCRE, PCCRE, FECCRE)
  VALUES (3, 4, 'Shampoo Medicado', 'Shampoo para dermatitis en mascotas', 42.00, 30, '1', 'admin', 'PC01', GETDATE());
  INSERT INTO PRODUCTO (IDUNIDAD_MEDIDA, IDCATEGORIA, NOMPRODUCTO, DESCRIPCION, PRECIO_UNITARIO, STOCK_ACTUAL, ESTADO, USUCRE, PCCRE, FECCRE)
  VALUES (3, 5, 'Vacuna Antirabica', 'Vacuna contra la rabia canina', 55.00, 200, '1', 'admin', 'PC01', GETDATE());
END
GO


-- INCLUYE VERSION (Optimistic Locking) y ESTADO para Soft Delete
-- ------------------------------------------------------------
USE BD_CONSOLIDADO;
GO
IF OBJECT_ID('dbo.PRODUCTO_CONSOLIDADO','U') IS NULL
BEGIN
  CREATE TABLE dbo.PRODUCTO_CONSOLIDADO(
    ID_REGISTRO      INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ID_PRODUCTO      VARCHAR(30)   NULL,
    NOMPRODUCTO      VARCHAR(100)  NULL,
    DESCRIPCION      VARCHAR(250)  NULL,
    CATEGORIA        VARCHAR(80)   NULL,
    PRECIO_UNITARIO  DECIMAL(10,2) NULL,
    COSTO_UNITARIO   VARCHAR(20)   NULL,
    STOCK_ACTUAL     VARCHAR(20)   NULL,
    MARCA            VARCHAR(50)   NULL,
    ESTADO           VARCHAR(20)   NULL DEFAULT 'A',
    VERSION          INT           NOT NULL DEFAULT 0,
    BD_ORIGEN        NVARCHAR(50)  NULL,
    FECH_CARGA       DATETIME      NULL DEFAULT GETDATE(),
    USUCRE           VARCHAR(30)   NULL,
    PCCRE            VARCHAR(30)   NULL,
    FECCRE           VARCHAR(30)   NULL,
    USUMOD           VARCHAR(30)   NULL,
    PCMOD            VARCHAR(30)   NULL,
    FECMOD           VARCHAR(30)   NULL
  );
END
GO

-- ------------------------------------------------------------
-- BD_CONSOLIDADO.OUTBOX
-- Tabla para mensajeria asincrona (Polling con UPDLOCK/READPAST)
-- ------------------------------------------------------------
IF OBJECT_ID('dbo.OUTBOX','U') IS NULL
BEGIN
  CREATE TABLE dbo.OUTBOX(
    ID_OUTBOX       BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    TABLA_DESTINO   VARCHAR(100)  NOT NULL,
    ID_REGISTRO     INT           NOT NULL,
    OPERACION       VARCHAR(10)   NOT NULL,
    PAYLOAD         VARCHAR(MAX)  NULL,
    ESTADO_SYNC     VARCHAR(20)   NOT NULL DEFAULT 'PENDIENTE',
    INTENTOS        INT           NOT NULL DEFAULT 0,
    BD_DESTINO      VARCHAR(100)  NOT NULL,
    FECHA_CREACION  DATETIME      NOT NULL DEFAULT GETDATE(),
    FECHA_PROCESO   DATETIME      NULL,
    MENSAJE_ERROR   VARCHAR(500)  NULL
  );
  CREATE INDEX IX_OUTBOX_ESTADO ON dbo.OUTBOX(ESTADO_SYNC, FECHA_CREACION)
    INCLUDE (ID_REGISTRO, TABLA_DESTINO, PAYLOAD, BD_DESTINO);
END
GO

-- ------------------------------------------------------------
-- BD_CONSOLIDADO.USUARIO
-- ------------------------------------------------------------
USE BD_CONSOLIDADO;
GO
IF OBJECT_ID('dbo.USUARIO','U') IS NULL
BEGIN
  CREATE TABLE dbo.USUARIO(
    ID_USUARIO     INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    USERNAME       VARCHAR(50)  NOT NULL UNIQUE,
    PASSWORD_HASH  VARCHAR(255) NOT NULL,
    ROL            VARCHAR(20)  NOT NULL DEFAULT 'USER',
    ESTADO         CHAR(1)      NULL DEFAULT 'A'
  );
END
GO
IF NOT EXISTS (SELECT 1 FROM USUARIO WHERE USERNAME='admin')
  INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, ROL)
  VALUES ('admin', '$2a$10$K.cYJjRBnNYWihyK/IvbyuFjcuk.8.GmcldLNJOoTBN4rDhUmc0ce', 'ADMIN');
GO
IF NOT EXISTS (SELECT 1 FROM USUARIO WHERE USERNAME='user')
  INSERT INTO USUARIO (USERNAME, PASSWORD_HASH, ROL)
  VALUES ('user', '$2a$10$K.cYJjRBnNYWihyK/IvbyuFjcuk.8.GmcldLNJOoTBN4rDhUmc0ce', 'USER');
GO

PRINT 'Bases y tablas listas.';
GO