UPDATE BD_CONSOLIDADO.dbo.USUARIO SET PASSWORD_HASH = '$2a$10$IarQ6uhziQQWLo8gpHse4OcMTb37gjrGo0EPmuHFj7bWA027Fu0Qu' WHERE USERNAME = 'admin';
UPDATE BD_CONSOLIDADO.dbo.USUARIO SET PASSWORD_HASH = '$2a$10$IarQ6uhziQQWLo8gpHse4OcMTb37gjrGo0EPmuHFj7bWA027Fu0Qu' WHERE USERNAME = 'user';
