jwt.secret=Consolidado2025SecretKeyQueDebeSerLargaParaHMACSHA256!
jwt.expiration=86400000

spring.datasource.consolidado.jdbc-url=jdbc:sqlserver://host.docker.internal:64419;databaseName=BD_CONSOLIDADO;encrypt=false;trustServerCertificate=true
spring.datasource.consolidado.username=sa
spring.datasource.consolidado.password=Castillon@2025
spring.datasource.consolidado.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.datasource.veterinaria.jdbc-url=jdbc:sqlserver://host.docker.internal:64419;databaseName=BD_CASTILLON_VETERINARIA;encrypt=false;trustServerCertificate=true
spring.datasource.veterinaria.username=sa
spring.datasource.veterinaria.password=Castillon@2025
spring.datasource.veterinaria.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver